#!groovy
podTemplate(
  label: "skopeo-pod",
  cloud: "openshift",
  inheritFrom: "maven",
  containers: [
    containerTemplate(
      name: "jnlp",
      image: "docker-registry.default.svc:5000/${GUID}-jenkins/jenkins-agent-appdev",
      resourceRequestMemory: "1Gi",
      resourceLimitMemory: "2Gi",
      resourceRequestCpu: "1",
      resourceLimitCpu: "2"
    )
  ]
) {
  node('skopeo-pod') {
    // Define Maven Command to point to the correct
    // settings for our Nexus installation
    def mvnCmd = "mvn -s ../nexus_settings.xml"

    // Checkout Source Code.
    stage('Checkout Source') {
      checkout scm
    }

    // Build the Tasks Service
    dir('openshift-tasks') {
      // The following variables need to be defined at the top level
      // and not inside the scope of a stage - otherwise they would not
      // be accessible from other stages.
      // Extract version from the pom.xml
      def version = getVersionFromPom("pom.xml")

      // Set the tag for the development image: version + build number
      def devTag  = "${version}-" + currentBuild.number
      // Set the tag for the production image: version
      def prodTag = "${version}"
      // Set Development and Production Project Names
      def devProject = "${GUID}-tasks-dev"
      def prodProject = "${GUID}-tasks-prod"
      def prefix = "gpte-hw"
      def cluster= "na311.openshift"

      // Using Maven build the war file
      // Do not run tests in this step
      stage('Build war') {
        echo "Building version ${devTag}"

        // Execute Maven Build
        sh "${mvnCmd} clean package -DskipTests=true"
      }

      // The next two stages should run in parallel
      parallel MavenUnitTest: {
        // Using Maven run the unit tests
        stage('Unit Tests') {
          echo "Running Unit Tests"
          // Execute Unit Tests
          sh "${mvnCmd} test"
          // This next step is optional.
          // It displays the results of tests in the Jenkins Task Overview
          step([$class: 'JUnitResultArchiver', testResults: '**/target/surefire-reports/TEST-*.xml'])
        }
      }, Sonarqube Code Analysis: {
        // Using Maven to call SonarQube for Code Analysis
        stage('Code Analysis') {
          echo "Running Code Analysis"
          // Execute Sonarqube Tests
          sh "${mvnCmd} sonar:sonar -Dsonar.host.url=http://sonarqube-${prefix}-cicd.apps.${cluster}.opentlc.com/" // -DskipTests=true
        }
      }

      // Publish the built war file to Nexus
      stage('Publish to Nexus') {
        echo "Publish to Nexus"
        // Publish to Nexus
        sh "${mvnCmd} deploy -DskipTests=true -DaltDeploymentRepository=nexus::default::http://nexus3.${prefix}-cicd.svc.cluster.local:8081/repository/all-maven-public"
      }

      // Build the OpenShift Image in OpenShift and tag it.
      stage('Build and Tag OpenShift Image') {
        steps {
          echo "Building OpenShift container image tasks:${devTag}"

          // Start Binary Build in OpenShift using the file we just published
          // The filename is openshift-tasks.war in the 'target' directory of your current
          // Jenkins workspace
          script {
            openshift.withCluster() {
              openshift.withProject("${devProject}") {
                openshift.selector("bc", "tasks").startBuild("--from-file=./target/openshift-tasks.war", "--wait=true")

              // Tag the image using the devTag
              openshift.tag("tasks:latest", "tasks:${devTag}")
              }
            }
          }
        }
      }

      // Deploy the built image to the Development Environment.
      stage('Deploy to Dev') {
        steps {
          echo "Deploy container image to Development Project"
          script {
            // 1. Update the image on the dev deployment config
            openshift.withCluster() {
              openshift.withProject("${devProject}") {
                // Set Image, Set VERSION


                // Update the Image on the Development Deployment Config
                def dc = openshift.selector("dc/tasks").object()
                // Set Image, Set VERSION
                dc.spec.template.spec.containers[0].image="docker-registry.default.svc:5000/${devProject}/tasks:${devTag}"
                dc.spec.template.spec.containers[0].env[0].value='${devTag} (tasks-dev)'

                // 2. Update the config maps with the potentially changed properties files
                openshift.selector('configmap', 'tasks-config').delete()
                def configmap = openshift.create('configmap', 'tasks-config', '--from-file=./configuration/application-users.properties', '--from-file=./configuration/application-roles.properties' )
                // 3. Reeploy the dev deployment
                openshift.selector("dc", "tasks").rollout().latest();
                // 4. Wait until the deployment is running
                //    The following code will accomplish that by
                //    comparing the requested replicas
                //    (rc.spec.replicas) with the running replicas
                //    (rc.status.readyReplicas)
                //
                def dc_version = dc.status.latestVersion
                def rc = openshift.selector("rc", "tasks-${dc_version}").object()

                //      Make sure the application is running and ready before proceeding
                echo "Waiting for ReplicationController tasks-${dc_version} to be ready"
                while (rc.spec.replicas != rc.status.readyReplicas) {
                  sleep 5
                  rc = openshift.selector("rc", "tasks-${dc_version}").object()
                } // end while
              } // end withProject
            } // end witchCluster
          } // end script
        } // end steps
      } // end stage

      // Copy Image to Nexus container registry
      stage('Copy Image to Nexus container registry') {
        steps {
          echo "Copy image to Nexus container Registry"
          script {
            // Use skopeo to copy
            sh "skopeo copy --src-tls-verify=false --dest-tls-verify=false --src-creds openshift:\$(oc whoami -t) --dest-creds admin:admin123 docker://image-registry.openshift-image-registry.svc.cluster.local:5000/${devProject}/tasks:${devTag} docker://nexus3-registry.${prefix}-cicd.svc.cluster.local:5000/tasks:${devTag}"

            // Tag the built image with the production tag.
            openshift.withCluster() {
              openshift.withProject("${prodProject}") {
                openshift.tag("${devProject}/tasks:${devTag}", "${devProject}/tasks:${prodTag}")
              } // end withProject
            } // end withCluster
          } // end script
        } // end steps
      } // end stage

      // Blue/Green Deployment into Production
      // -------------------------------------
      def destApp   = "tasks-green"
      def activeApp = ""

      stage('Blue/Green Production Deployment') {
        steps {
          echo "Blue/Green Deployment"
          script {
            // 1. Determine which application is active
            openshift.withCluster() {
              openshift.withProject("${prodProject}") {
                activeApp = openshift.selector("route", "tasks").object().spec.to.name
                if (activeApp == "tasks-green") {
                  destApp = "tasks-blue"
                }
                echo "Active Application:      " + activeApp
                echo "Destination Application: " + destApp

            // 2. Update the image for the other application

                // Update the Image on the Production Deployment Config
                def dc = openshift.selector("dc/${destApp}").object()
                // Set Image, Set VERSION
                dc.spec.template.spec.containers[0].image="docker-registry.default.svc:5000/${devProject}/tasks:${prodTag}"
                dc.spec.template.spec.containers[0].env[0].value='${prodTag} (${activeApp})'

                // Update Config Map in change config files changed in the source
                openshift.selector("configmap", "${destApp}-config").delete()
                def configmap = openshift.create("configmap", "${destApp}-config", "--from-file=./configuration/application-users.properties", "--from-file=./configuration/application-roles.properties" )

            // 3. Deploy into the other application
                // Deploy the inactive application.
                openshift.selector("dc", "${destApp}").rollout().latest();
            // 4. Update Config maps for other application
            // 5. Wait until application is running

                // Wait for application to be deployed
                def dc_prod = openshift.selector("dc", "${destApp}").object()
                def dc_version = dc_prod.status.latestVersion
                def rc_prod = openshift.selector("rc", "${destApp}-${dc_version}").object()
                // Make sure the application is running and ready before proceeding
                echo "Waiting for ${destApp} to be ready"
                while (rc_prod.spec.replicas != rc_prod.status.readyReplicas) {
                  sleep 5
                  rc_prod = openshift.selector("rc", "${destApp}-${dc_version}").object()
                } // end while
              } // end withProject
            } // end withCluster
          } // end script
        } // end steps
      } // end stage

      stage('Switch over to new Version') {
        steps {
          // Stop for approval
          input "Switch Production?"

          echo "Executing production switch"
          // After approval execute the switch
          echo "Switching Production application to ${destApp}."
          script {
            openshift.withCluster() {
              openshift.withProject("${prodProject}") {
                def route = openshift.selector("route/tasks").object()
                route.spec.to.name="${destApp}"
                openshift.apply(route)
              } // end withProject
            } // end withCluster
          } // end script
        } // end stage
      } // end stage

    } // end dir
  } // end node
} // end podTemplate

// Convenience Functions to read version from the pom.xml
// Do not change anything below this line.
// --------------------------------------------------------
def getVersionFromPom(pom) {
  def matcher = readFile(pom) =~ '<version>(.+)</version>'
  matcher ? matcher[0][1] : null
}